var = input("Escreva algo:")

print("{} é do tipo primitivo".format(var), type(var))
print("{} possui apenas números?".format(var), var.isnumeric())
print("{} possui apenas letras?".format(var), var.isalpha())
print("{} possui letras/números?".format(var), var.isalnum())
print("{} é um espaço?".format(var), var.isspace())
print("{} é um número sem vírgula?".format(var), var.isdecimal())
print("{} contém apenas dígitos?".format(var), var.isdigit())
print("{} está escrito em letras minúsculas apenas?".format(var), var.islower())
print("{} está escrito em letras maiúsculas apenas?".format(var), var.isupper())
print("{} é um identificador válido?".format(var), var.isidentifier())
print("{} é printável?".format(var), var.isprintable())
print("{} os caracteres pertencem ao ASCII?".format(var), var.isascii())
print("{} Todas as palavras começam com letra maiúscula?".format(var), var.istitle())